Add setup files
ZoundLoud/service-pon-y pull request #1
Opened 2019-02-06 23:47 UTC by pon-y

Add webpack file and initial react test

2019-02-06 23:53 UTC, kevinbece5 requested changes
Hey, could you make sure you are using the Airbnb style guide

2019-02-07 01:05 UTC, sharmoo reviewed
remove hr linter in favor of Airbnb

2019-02-07 01:32 UTC, pon-y commented
@kevinbece5 @sharmoo Updates with AirBnB style guide and eslint. Please check to see if it is correct

2019-02-07 03:07 UTC, kevinbece5 approved these changes

2019-02-07 03:29 UTC, merged